### ISSUE TITLE
Generate minified versions too.

### ISSUE THREAD

**Issue by jpink** [Download/polymer-cdn#13]
Hi,

current components are well documented and good for development. In production environment they should be minimized. HTML, CSS ja JavaScript can be made smaller:
- All comments can be removed.
- Whitespace and indenting can be removed.
- so on.

This isn't major problem and this CDN approach fights against Polymers best practices:
- Use bower
- Build your app using polymer-cli

Do you have any ideas to minify current files easily. E.g. renaming paper-input/paper-input.html to paper-input/paper-input**.min**.html or something.

**Comment by Download** [comment]
Sorry for the late response.
I consider minifying to be out of scope for this project.

You are right of course. In production, you *should* minify your files. But even more important, in production you should *bundle* the files together so you don't get the latency that comes with firing 2 dozen requests for .html, .js and .css files. Using a dozen minified files is still no good solution in production.

This CDN is very suitable for things like JSFiddle, CodePen or quick and dirty hacking together something. For production work, you really need a toolchain.
