### ISSUE TITLE
[bug] Polymer 2 is not provided properly

### ISSUE THREAD

**Issue by keradus** [Download/polymer-cdn#19]
When I want to load polymer 2:
```
  <script src="https://cdn.rawgit.com/download/polymer-cdn/2.0.1/lib/webcomponentsjs/webcomponents-loader.js"></script>
  <link rel="import" href="https://cdn.rawgit.com/download/polymer-cdn/2.0.1/lib/polymer/polymer.html">
```

what I got is Polymer **1.9**
as you can see in readme file, everywhere is `polymer#1.9.2` instead of 2.x

**Comment by Download** [comment]
Yes you are right. Sorry about that and thanks for reporting it.
I have fixed it I think. Can you please verify that [release 2.0.2](https://github.com/Download/polymer-cdn/releases/tag/2.0.2). fixes it for you?

**Comment by keradus** [comment]
sorry, as there were no answer for almost 2 weeks I drop using this package.
thanks for fix, yet I won't be able to confirm it
