### ISSUE TITLE
Unable to down Polymer#^2.0 version in bower

### ISSUE THREAD

**Issue by vignesh290489** [Download/polymer-cdn#21]
unable to download polymer 2.0 all elements(iron,paper,..) through bower. Can't we download all elements at one shot ? Am i missing something ?

**sample error :**  bower paper-badge#^1.0.0                      ECMDERR Failed to execute "C:\Changeller\Changeller\Changeller\.bin\git.CMD ls-remote --tags --heads git://github.com/PolymerElements/paper-badge.git", ex
it code of #8**

**Comment by Download** [comment]
This repo offers a CDN version of Polymer. That means we bypass NPM / Bower etc and include directly in the HTML page, via the CDN url. Have a look at the Code Pen mentioned in the readme.
