### ISSUE TITLE
Update polymer to 1.11.0

### ISSUE THREAD

**Issue by paladox** [Download/polymer-cdn#22]
Hi, please could you provide polymer 1.11.0?

**Comment by Download** [comment]
Sorry I don't have the time ATM.
I would welcome a PR though!

If you want to try, then fork this repo, clone the fork to your local machine, switch branch to the last 1.x version and then try to upgrade that to 1.11.0. Use Bower to upgrade. If you succeed you can then commit the changes you made, push to the fork and send a PR here.
