### ISSUE TITLE
Update polymer to 2.3.1

### ISSUE THREAD

**Issue by ltomes** [Download/polymer-cdn#23]
Could you please release a branch of Polymer 2.3.1?

Thanks!

Related code fork:
https://github.com/Download/polymer-cdn/pull/24

Notes: `iron-flex-layout` does not seem to be working as expected yet

**Comment by Download** [comment]
Thanks for that great PR!
https://github.com/Download/polymer-cdn/pull/24

Released as 2.3.1:
https://github.com/Download/polymer-cdn/releases/tag/2.3.1
