### ISSUE TITLE
You sir are awesome. - #notanissue

### ISSUE THREAD

**Issue by azariah001** [Download/polymer-cdn#3]
I know github issues isn't the place to put this but... I don't know where else to say thank you so.

Thank you! :grinning: 

I don't know why but... installing Polymer using Bower yields... 3 different versions of broken :see_no_evil: No idea how or why (if I had to hazard a guess the fact that bower points straight at the repo's might be part of the problem) but.... you're repository just saved me from my headache.  :grinning: Not using it with the CDN but being able to do a single all inclusive download is awesome. I remember the first version of Polymer you could do that but... now. There's almost nothing in the quickstart zip. Anyway.

Downloaded refreshed the page and.... everything works. :+1: thanks man. :smile: 

close

**Comment by azariah001** [comment]
close

**Comment by Download** [comment]
Ha ha thank you! You made my day! 

Don't worry about using issues for comments. Especially if they are as warm as this one!  :)

Let me know if you are missing something and I'll do my best to add it. And if you like polymer-cdn, please star my repo.
