### ISSUE TITLE
Version number issues

### ISSUE THREAD

**Issue by Download** [Download/polymer-cdn#30]
@FuriosoJack Thank you for accepting the invite! I see you are putting your new powers to good use. Thank you for the new release! However, a couple of remarks:

1. For the version number, we try to follow the Polymer version as close as possible. So prev release was named `'2.6.0'` because that was the Polymer version. This release does not update the Polymer version, so the version number should reflect that by keeping the first 3 numbers the same and adding a 4th number to indicate the intermediate update: => `'2.6.0.2'`

2. You named the tag `'v2.6.1'`, but I always left out the `'v'` in the tag. So I renamed it to `'2.6.0.2'` for consistency.

3. You forgot to update the README. It contains some version numbers. I usually do a Search => Replace, making sure not to mess with the versions in the Bower dependency tree at the bottom. Speaking of which, you probably also need to update that one. It's just the result of `bower list`, making sure to remove the path name on the first line.

I tried to describe this as best I could in the [Contribution Guide](https://github.com/Download/polymer-cdn/blob/master/CONTRIBUTING.md). It may be helpful to have a look at that again.

Thanks again for contributing!

-Stijn

**Comment by FuriosoJack** [comment]
done partner, what a shame with you, I had not had time

**Comment by Download** [comment]
No problem, great job and thanks for collaborating!
