### ISSUE TITLE
not able to use paper-input from cdn

### ISSUE THREAD

**Issue by pkgulati** [Download/polymer-cdn#4]
<link rel="import" href="https://raw.githubusercontent.com/Polymer/paper-input/master/paper-input.html">
internally tries to load
https://raw.githubusercontent.com/Polymer/paper-input/polymer/polymer.html

**Comment by Download** [comment]
Can you give more info?
What URL did you use to include the element?
Do you have a JSFiddle demonstrating the issue?

**Comment by Download** [comment]
Closing due to lack of response from OP
