### ISSUE TITLE
Upgrade to 1.6.1

### ISSUE THREAD

**Issue by jpink** [Download/polymer-cdn#9]
Hi!

There are now releases 1.6.1 (2016-08-01) and 1.6.0 (2016-06-29). Is it hard job to fix those imports or do you have a find & replace script or something?

**Comment by Download** [comment]
Hi @jpink,

Actually it isn't hard at all. I'm just not working with polymer anymore atm, so I'm not keeping so close tabs. Which is bad... Also you had to wait for 18 days for a response, which is also bad!  Sorry!

What I should do is create a simple step by step guide to empower people like you to easily step in and upgrade to the version you need on your own fork. Let me have a look if I can cook something up.

**Comment by Download** [comment]
@jpink Ok, I just updated to 1.6.0. Will do 1.6.1. next. 

Also, I created a [Contribution Guide](https://github.com/Download/polymer-cdn/blob/master/CONTRIBUTING.md), so if you ever find you need a new version and it's not here yet, you can update it on your own fork and send us a PR.

**Comment by Download** [comment]
1.6.1. is also available now.

**Comment by jpink** [comment]
Thanks for update and the Guide. Next time i'll try myself.
